name: Telegram notification

on:
  push:
    branches: [ dev ]

jobs:

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          PUSHED TO DEV:
          FROM COMMIT:
          ${{ github.event.commits[0].message }}
          TO COMMIT:
          ${{ github.event.head_commit.message }}

          DON'T FORGET TO "git pull origin dev" !!!!
